export const restaurants = [
  {
    id: 'hardees-jt',
    name: "Hardee's Johar Town",
    type: 'Fast Food',
    description: 'Burgers & fries',
    latitude: 31.4708,
    longitude: 74.2721,
  },
  {
    id: 'mcd-jt',
    name: "McDonald's Johar Town",
    type: 'Fast Food',
    description: 'Global chain',
    latitude: 31.4715,
    longitude: 74.2685,
  },
  {
    id: 'kfc-jt',
    name: 'KFC Johar Town',
    type: 'Fast Food',
    description: 'Fried chicken',
    latitude: 31.4727,
    longitude: 74.2758,
  },
  {
    id: 'johnnyjugnu-jt',
    name: 'Johnny & Jugnu Johar Town',
    type: 'Fast Food',
    description: 'Wraps & burgers',
    latitude: 31.4689,
    longitude: 74.2791,
  },
  {
    id: 'optp-jt',
    name: 'OPTP Johar Town',
    type: 'Fast Food',
    description: 'One Potato Two Potato',
    latitude: 31.4741,
    longitude: 74.2702,
  },
  {
    id: 'forks-jt',
    name: 'Forks N Knives Johar Town',
    type: 'Pizza',
    description: 'Pizza & more',
    latitude: 31.4676,
    longitude: 74.2709,
  },
  {
    id: 'bundu-jt',
    name: 'Bundu Khan Johar Town',
    type: 'Pakistani',
    description: 'BBQ & desi',
    latitude: 31.4699,
    longitude: 74.2655,
  },
  {
    id: 'howdy-jt',
    name: 'Howdy Johar Town',
    type: 'Burgers',
    description: 'Steak & burgers',
    latitude: 31.4733,
    longitude: 74.2781,
  },
  {
    id: 'frichicks-jt',
    name: 'Fri Chicks Johar Town',
    type: 'Fast Food',
    description: 'Chicken & pizza',
    latitude: 31.4669,
    longitude: 74.2732,
  },
  {
    id: 'arcadian-jt',
    name: 'Arcadian Cafe Johar Town',
    type: 'Cafe',
    description: 'Continental & cafe',
    latitude: 31.4751,
    longitude: 74.2677,
  },
];